# Generated by Django 5.0.2 on 2024-02-29 11:26

import users.models
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                upload_to=users.models.profile_image_path,
                validators=[users.validators.validate_profile_image_extension],
            ),
        ),
    ]
